//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.26 at 06:13:38 PM GMT-03:00 
//


package mining.challenge.android.bugreport.model;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;

import br.ufba.dcc.disciplinas.mate08.model.BaseEntity;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}bugid"/>
 *         &lt;element ref="{}title"/>
 *         &lt;element ref="{}status"/>
 *         &lt;element ref="{}owner"/>
 *         &lt;element ref="{}closedOn"/>
 *         &lt;element ref="{}type"/>
 *         &lt;element ref="{}priority"/>
 *         &lt;element ref="{}component"/>
 *         &lt;element ref="{}stars"/>
 *         &lt;element ref="{}reportedBy"/>
 *         &lt;element ref="{}openedDate"/>
 *         &lt;element ref="{}description"/>
 *         &lt;element ref="{}comment" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "bugid",
    "title",
    "status",
    "owner",
    "closedOn",
    "type",
    "priority",
    "component",
    "stars",
    "reportedBy",
    "openedDate",
    "description",
    "comment"
})
@XmlRootElement(name = "bug")
@Entity(name = "Bug")
@Table(name = "BUG")
@Inheritance(strategy = InheritanceType.JOINED)
public class Bug
    implements Equals, HashCode, BaseEntity<BigInteger>
{
/**
	 * 
	 */
	private static final long serialVersionUID = 7023878639445840814L;

    @XmlElement(required = true)
    protected BigInteger bugid;
    @XmlElement(required = true)
    protected String title;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NCName")
    protected String status;
    @XmlElement(required = true)
    protected String owner;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "NMTOKEN")
    protected String closedOn;
    @XmlElement(required = true)
    protected String type;
    @XmlElement(required = true)
    protected String priority;
    @XmlElement(required = true)
    protected String component;
    @XmlElement(required = true)
    protected BigInteger stars;
    @XmlElement(required = true)
    protected String reportedBy;
    @XmlElement(required = true)
    protected String openedDate;
    @XmlElement(required = true)
    protected String description;
    protected List<Comment> comment;
    @XmlAttribute(name = "Hjid")
    protected Long hjid;

    /**
     * Gets the value of the bugid property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "BUGID", precision = 20, scale = 0)
    public BigInteger getBugid() {
        return bugid;
    }

    /**
     * Sets the value of the bugid property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBugid(BigInteger value) {
        this.bugid = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "TITLE", length = 255)
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "STATUS", length = 255)
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the owner property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "OWNER_", length = 255)
    public String getOwner() {
        return owner;
    }

    /**
     * Sets the value of the owner property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOwner(String value) {
        this.owner = value;
    }

    /**
     * Gets the value of the closedOn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "CLOSEDON", length = 255)
    public String getClosedOn() {
        return closedOn;
    }

    /**
     * Sets the value of the closedOn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClosedOn(String value) {
        this.closedOn = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "TYPE_", length = 255)
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the priority property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "PRIORITY", length = 255)
    public String getPriority() {
        return priority;
    }

    /**
     * Sets the value of the priority property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPriority(String value) {
        this.priority = value;
    }

    /**
     * Gets the value of the component property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "COMPONENT", length = 255)
    public String getComponent() {
        return component;
    }

    /**
     * Sets the value of the component property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComponent(String value) {
        this.component = value;
    }

    /**
     * Gets the value of the stars property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Basic
    @Column(name = "STARS", precision = 20, scale = 0)
    public BigInteger getStars() {
        return stars;
    }

    /**
     * Sets the value of the stars property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setStars(BigInteger value) {
        this.stars = value;
    }

    /**
     * Gets the value of the reportedBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "REPORTEDBY", length = 255)
    public String getReportedBy() {
        return reportedBy;
    }

    /**
     * Sets the value of the reportedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReportedBy(String value) {
        this.reportedBy = value;
    }

    /**
     * Gets the value of the openedDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "OPENEDDATE", length = 255)
    public String getOpenedDate() {
        return openedDate;
    }

    /**
     * Sets the value of the openedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOpenedDate(String value) {
        this.openedDate = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "DESCRIPTION", length = 255)
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the comment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the comment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getComment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Comment }
     * 
     * 
     */
    @OneToMany(targetEntity = Comment.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "COMMENT__BUG_HJID")
    public List<Comment> getComment() {
        if (comment == null) {
            comment = new ArrayList<Comment>();
        }
        return this.comment;
    }

    /**
     * 
     * 
     */
    public void setComment(List<Comment> comment) {
        this.comment = comment;
    }

    /**
     * Gets the value of the hjid property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @Id
    @Column(name = "HJID")
    @GeneratedValue(strategy = GenerationType.AUTO)
    public Long getHjid() {
        return hjid;
    }

    /**
     * Sets the value of the hjid property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setHjid(Long value) {
        this.hjid = value;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if (!(object instanceof Bug)) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final Bug that = ((Bug) object);
        {
            BigInteger lhsBugid;
            lhsBugid = this.getBugid();
            BigInteger rhsBugid;
            rhsBugid = that.getBugid();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "bugid", lhsBugid), LocatorUtils.property(thatLocator, "bugid", rhsBugid), lhsBugid, rhsBugid)) {
                return false;
            }
        }
        {
            String lhsTitle;
            lhsTitle = this.getTitle();
            String rhsTitle;
            rhsTitle = that.getTitle();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "title", lhsTitle), LocatorUtils.property(thatLocator, "title", rhsTitle), lhsTitle, rhsTitle)) {
                return false;
            }
        }
        {
            String lhsStatus;
            lhsStatus = this.getStatus();
            String rhsStatus;
            rhsStatus = that.getStatus();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "status", lhsStatus), LocatorUtils.property(thatLocator, "status", rhsStatus), lhsStatus, rhsStatus)) {
                return false;
            }
        }
        {
            String lhsOwner;
            lhsOwner = this.getOwner();
            String rhsOwner;
            rhsOwner = that.getOwner();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "owner", lhsOwner), LocatorUtils.property(thatLocator, "owner", rhsOwner), lhsOwner, rhsOwner)) {
                return false;
            }
        }
        {
            String lhsClosedOn;
            lhsClosedOn = this.getClosedOn();
            String rhsClosedOn;
            rhsClosedOn = that.getClosedOn();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "closedOn", lhsClosedOn), LocatorUtils.property(thatLocator, "closedOn", rhsClosedOn), lhsClosedOn, rhsClosedOn)) {
                return false;
            }
        }
        {
            String lhsType;
            lhsType = this.getType();
            String rhsType;
            rhsType = that.getType();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "type", lhsType), LocatorUtils.property(thatLocator, "type", rhsType), lhsType, rhsType)) {
                return false;
            }
        }
        {
            String lhsPriority;
            lhsPriority = this.getPriority();
            String rhsPriority;
            rhsPriority = that.getPriority();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "priority", lhsPriority), LocatorUtils.property(thatLocator, "priority", rhsPriority), lhsPriority, rhsPriority)) {
                return false;
            }
        }
        {
            String lhsComponent;
            lhsComponent = this.getComponent();
            String rhsComponent;
            rhsComponent = that.getComponent();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "component", lhsComponent), LocatorUtils.property(thatLocator, "component", rhsComponent), lhsComponent, rhsComponent)) {
                return false;
            }
        }
        {
            BigInteger lhsStars;
            lhsStars = this.getStars();
            BigInteger rhsStars;
            rhsStars = that.getStars();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "stars", lhsStars), LocatorUtils.property(thatLocator, "stars", rhsStars), lhsStars, rhsStars)) {
                return false;
            }
        }
        {
            String lhsReportedBy;
            lhsReportedBy = this.getReportedBy();
            String rhsReportedBy;
            rhsReportedBy = that.getReportedBy();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "reportedBy", lhsReportedBy), LocatorUtils.property(thatLocator, "reportedBy", rhsReportedBy), lhsReportedBy, rhsReportedBy)) {
                return false;
            }
        }
        {
            String lhsOpenedDate;
            lhsOpenedDate = this.getOpenedDate();
            String rhsOpenedDate;
            rhsOpenedDate = that.getOpenedDate();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "openedDate", lhsOpenedDate), LocatorUtils.property(thatLocator, "openedDate", rhsOpenedDate), lhsOpenedDate, rhsOpenedDate)) {
                return false;
            }
        }
        {
            String lhsDescription;
            lhsDescription = this.getDescription();
            String rhsDescription;
            rhsDescription = that.getDescription();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "description", lhsDescription), LocatorUtils.property(thatLocator, "description", rhsDescription), lhsDescription, rhsDescription)) {
                return false;
            }
        }
        {
            List<Comment> lhsComment;
            lhsComment = (((this.comment!= null)&&(!this.comment.isEmpty()))?this.getComment():null);
            List<Comment> rhsComment;
            rhsComment = (((that.comment!= null)&&(!that.comment.isEmpty()))?that.getComment():null);
            if (!strategy.equals(LocatorUtils.property(thisLocator, "comment", lhsComment), LocatorUtils.property(thatLocator, "comment", rhsComment), lhsComment, rhsComment)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = 1;
        {
            BigInteger theBugid;
            theBugid = this.getBugid();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "bugid", theBugid), currentHashCode, theBugid);
        }
        {
            String theTitle;
            theTitle = this.getTitle();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "title", theTitle), currentHashCode, theTitle);
        }
        {
            String theStatus;
            theStatus = this.getStatus();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "status", theStatus), currentHashCode, theStatus);
        }
        {
            String theOwner;
            theOwner = this.getOwner();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "owner", theOwner), currentHashCode, theOwner);
        }
        {
            String theClosedOn;
            theClosedOn = this.getClosedOn();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "closedOn", theClosedOn), currentHashCode, theClosedOn);
        }
        {
            String theType;
            theType = this.getType();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "type", theType), currentHashCode, theType);
        }
        {
            String thePriority;
            thePriority = this.getPriority();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "priority", thePriority), currentHashCode, thePriority);
        }
        {
            String theComponent;
            theComponent = this.getComponent();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "component", theComponent), currentHashCode, theComponent);
        }
        {
            BigInteger theStars;
            theStars = this.getStars();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "stars", theStars), currentHashCode, theStars);
        }
        {
            String theReportedBy;
            theReportedBy = this.getReportedBy();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "reportedBy", theReportedBy), currentHashCode, theReportedBy);
        }
        {
            String theOpenedDate;
            theOpenedDate = this.getOpenedDate();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "openedDate", theOpenedDate), currentHashCode, theOpenedDate);
        }
        {
            String theDescription;
            theDescription = this.getDescription();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "description", theDescription), currentHashCode, theDescription);
        }
        {
            List<Comment> theComment;
            theComment = (((this.comment!= null)&&(!this.comment.isEmpty()))?this.getComment():null);
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "comment", theComment), currentHashCode, theComment);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

	@Override
	public BigInteger getId() {		
		return getBugid();
	}

	@Override
	public void setId(BigInteger id) {
		setBugid(id);		
	}

}
